In [1]:
!pip install google-api-python-client

Requirement already satisfied: google-api-python-client in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.198.0)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from google-api-python-client) (0.32.0)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from google-api-python-client) (2.55.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from google-api-python-client) (0.4.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from google-api-python-client) (2.31.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from google-api-python-client) (4.2.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=5.29.6 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (7.35.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.24.0 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.28.1)
Requirement already satisfied: requests<3.0.0,>=2.33.0 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.34.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (46.0.5)
Requirement already satisfied: pyparsing<4,>=3.1 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.6.2)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2025.11.12)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (2.0.0)
Requirement already satisfied: pycparser in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in C:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.6.4)

In [1]:
from googleapiclient.discovery import build
import pandas as pd
from tqdm.auto import tqdm
import time

c:\Users\herre\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
import os

clave = os.getenv("YOUTUBE_API_KEY")

print("Clave encontrada:", bool(clave))
print("Formato probable:", clave.startswith("AIza") if clave else False)

Clave encontrada: True
Formato probable: True

In [3]:
import os
from googleapiclient.discovery import build

API_KEY = os.getenv("YOUTUBE_API_KEY")

if not API_KEY:
    raise RuntimeError(
        "No se ha definido la variable de entorno "
        "YOUTUBE_API_KEY"
    )

youtube = build(
    "youtube",
    "v3",
    developerKey=API_KEY
)

In [4]:
from pathlib import Path

BASE = Path(
    r"C:\Users\herre\OneDrive\Desktop\Proyectos DATA\SPRINT 13"
)

RUTA_RAW = (
    BASE
    / "01_data"
    / "01_raw"
    / "rrss"
    / "youtube"
)

RUTA_RAW.mkdir(
    parents=True,
    exist_ok=True
)

print("RAW YouTube:", RUTA_RAW)

RAW YouTube: C:\Users\herre\OneDrive\Desktop\Proyectos DATA\SPRINT 13\01_data\01_raw\rrss\youtube

In [5]:
import os

clave = os.getenv("YOUTUBE_API_KEY")

print("Variable encontrada:", bool(clave))
print("Longitud:", len(clave) if clave else 0)
print("Sigue siendo el ejemplo:", clave == "TU_NUEVA_CLAVE_DE_YOUTUBE")

Variable encontrada: True
Longitud: 39
Sigue siendo el ejemplo: False

In [5]:
request = youtube.search().list(
    part="snippet",
    q="inmigración España",
    type="video",
    maxResults=10,
    relevanceLanguage="es",
    regionCode="ES"
)

response = request.execute()

len(response["items"])

10

In [9]:
videos = []

for item in response["items"]:
    videos.append({
        "video_id": item["id"]["videoId"],
        "titulo": item["snippet"]["title"],
        "descripcion": item["snippet"]["description"],
        "canal": item["snippet"]["channelTitle"],
        "fecha_publicacion": item["snippet"]["publishedAt"]
    })

df_videos = pd.DataFrame(videos)

df_videos

,video_id,titulo,descripcion,canal,fecha_publicacion
0,V21-0RMUAT8,🚨 COLAPSO MIGRATORIO | España registra avalanc...,Canal26 #Inmigración #España La aprobación de ...,Canal 26,2026-02-02T19:42:51Z
1,BU0rX-hNMv0,España regulariza a medio millón de migrantes:...,"Mientras Europa blinda sus fronteras, España p...",FRANCE 24 Español,2026-06-29T16:27:27Z
2,eCFL3zhaovY,INMIGRACIÓN - Salvación para España o Gran rem...,Es la inmigración la solución al colapso de Es...,NOTICIAS ILUSTRADAS,2026-02-09T15:27:02Z
3,EGI9XOUNvEg,"Los españoles, indignados con la regularizació...",Muchos españoles han denunciado ante el micróf...,LibertadDigital,2026-02-07T05:00:22Z
4,v_hsl1wgaHQ,vlog l INMIGRACIÓN ME OBLIGA A QUEDARME EN ESP...,"Music by oh, the joy. - 1pm in san francisco -...",James,2026-07-19T22:00:10Z
5,eM09M5crm5E,Así ve Aznar la inmigración en España,Crees que España necesita cambiar su política ...,Administrativando Abogados,2026-07-24T08:00:21Z
6,Y6Y37the4GQ,ESPAÑA cierra puertas a migrantes | La verdad ...,La situación migratoria en España es un tema d...,Hildemaro Solis,2026-04-01T21:18:46Z
7,bDkkwCyr_CE,Regularización masiva de INMIGRANTES en ESPAÑA,Cómo conseguir la regularización masiva de 202...,NOTICIAS ILUSTRADAS,2026-01-29T15:53:04Z
8,s8L7RCOlFs8,"La inmigración a debate: delincuencia, integra...",PARTE 1: https://youtu.be/inaqipYfLjs ¿Qué sig...,ConPdePodcast,2026-07-18T14:30:14Z
9,h3OBbS70xfw,La regularización extraordinaria en 2026: nuev...,Miles de migrantes viven en España sin papeles...,DW Español,2026-02-28T00:45:04Z

In [10]:
request = youtube.search().list(
    part="snippet",
    q="inmigración España",
    type="video",
    maxResults=50,
    relevanceLanguage="es",
    regionCode="ES",
    publishedAfter="2019-01-01T00:00:00Z",
    publishedBefore="2020-01-01T00:00:00Z",
    order="relevance"
)

response_2019 = request.execute()

In [7]:
videos_2019 = []

for item in response_2019["items"]:
    videos_2019.append({
        "video_id": item["id"]["videoId"],
        "titulo": item["snippet"]["title"],
        "descripcion": item["snippet"]["description"],
        "canal": item["snippet"]["channelTitle"],
        "fecha_publicacion": item["snippet"]["publishedAt"],
        "tema_busqueda": "inmigracion",
        "año_busqueda": 2019
    })

df_videos_2019 = pd.DataFrame(videos_2019)

df_videos_2019

,video_id,titulo,descripcion,canal,fecha_publicacion,tema_busqueda,año_busqueda
0,ne7WoOWstvg,¿Inmigrantes hispanoamericanos o magrebíes?,El sociólogo Amando de Miguel asegura que en E...,El Toro TV,2019-11-09T22:45:00Z,inmigracion,2019
1,oiX9Hou3hEY,INMIGRACIÓN en España en 3 minutos,La inmigración en España ha sido usada como ar...,Política en 3 minutos,2019-04-03T10:58:49Z,inmigracion,2019
2,Y5vVL5EFhCk,Abascal : “En VOX privilegiamos la inmigración...,Abascal : “En VOX privilegiamos la inmigración...,Españoles de Cuba,2019-07-22T18:57:24Z,inmigracion,2019
3,xF6IDLsIv_k,La policía española halla personas escondidas ...,El uso de colchones para esconder migrantes po...,euronews (en español),2019-01-01T13:17:05Z,inmigracion,2019
4,-Gytamy7G2E,España ya no es la principal entrada de inmigr...,"Según el ministerio del Interior, las llegadas...",euronews (en español),2019-06-19T09:50:39Z,inmigracion,2019
5,-ardA7cU6f0,Más de 30.000 inmigrantes ilegales en 2019: la...,Cuántos inmigrantes irregulares han entrado en...,El Toro TV,2019-12-18T11:47:20Z,inmigracion,2019
6,IurbEiV8xjU,Las mentiras de Vox sobre inmigración,El partido de Santiago Abascal también miente ...,Cadena SER,2019-11-07T11:56:17Z,inmigracion,2019
7,PUKFLX0T-iM,JUAN SOLAECHE:La mayoría de la inmigración ile...,Distrito Televisión es un canal de televisión ...,DISTRITOTV,2019-07-28T09:43:16Z,inmigracion,2019
8,8tLCJ6Q-hNc,DEBATE INMIGRACIÓN EN ESPAÑA,,Santiago Millan,2019-07-11T19:13:40Z,inmigracion,2019
9,GGQgDxjb8xQ,"España, un país de migrantes: los años en los ...",Andrea Ropero recuerda en el Intermedio cuando...,laSexta,2019-12-26T11:37:30Z,inmigracion,2019
10,Z5YzLgXEjg4,"La inmigración ilegal, desbordada en España",Suscríbete a nuestro nuevo canal ↙ ✓ https://w...,La Toroteca,2019-04-11T11:43:20Z,inmigracion,2019
11,4OuThKoZytQ,El gran problema del que nadie quiere hablar e...,Suscríbete a nuestro nuevo canal ↙ ✓ https://w...,La Toroteca,2019-01-10T14:16:36Z,inmigracion,2019
12,FiLIU2dpegQ,Santiago Abascal denuncia en el Congreso la pa...,Santiago Abascal denuncia en el Congreso las p...,VOX España,2019-08-05T19:20:03Z,inmigracion,2019
13,KA6NP4VoycU,"“¡España, España!, ¡el Estrecho!”: el grito ma...","En trajes de neopreno, en kayak o, los que pue...",FaroTV Ceuta,2019-09-07T18:44:43Z,inmigracion,2019
14,RuWO0NTPZus,🔴🔴🔴 OPEN ARMS y la Inmigración ilegal en ESPAÑ...,Buenos días señoras y sñores! Hoy vamos a habl...,La Nicoteca,2019-08-13T19:51:57Z,inmigracion,2019
15,EemzZxSxdlI,Así era la situación de España justo después d...,"Al terminar la Guerra Civil, España no estaba ...",DMAX España,2019-05-28T15:26:06Z,inmigracion,2019
16,3VmBYcMcLRU,Inmigrantes querían cruzar frontera en España ...,Más informaciones en » http://T13.cl Síguenos ...,Teletrece,2019-01-03T02:01:24Z,inmigracion,2019
17,ntc0kC9lI6A,Valla de Melilla: la peligrosa frontera que se...,Suscríbete a BBC Mundo http://vid.io/xqOx Meli...,BBC News Mundo,2019-07-04T16:58:18Z,inmigracion,2019
18,8PwWreXU3vU,"Santiago Abascal, entrevista 1ª parte: La unid...","Qué es España para Santiago Abascal?, ¿cuál es...",bichopedia,2019-04-09T07:44:12Z,inmigracion,2019
19,P3CFqc1PVlU,&quot;Cuando los españoles emigraban lo hacían...,Probablemente habrás escuchado muchas veces es...,Rugetistas RUGE,2019-10-30T12:23:40Z,inmigracion,2019
20,c0GGvFBMNsI,Los ecos de la inmigración española en Bélgica,"Bruselas (Bélgica), 19 jun (EFE).- (Imagen: An...",AGENCIA EFE,2019-06-20T10:55:57Z,inmigracion,2019
21,fyAlQMdBkjo,Los chalecos negros piden papeles para los inm...,Los chalecos negros piden papeles para los inm...,euronews (en español),2019-07-13T10:45:48Z,inmigracion,2019
22,Km3Heq7tnFw,España pide a la UE más ayudas para Marruecos ...,"Marruecos ha hecho su parte, la Unión Europea ...",euronews (en español),2019-06-04T08:06:09Z,inmigracion,2019
23,9-f4bcPDojU,El papa Francisco reflexiona sobre inmigración...,Todos lo capítulos completos de 'Salvados' en ...,laSexta,2019-04-07T19:46:01Z,inmigracion,2019
24,y-VAW93LWOg,Santiago Abascal en Roma &quot;España fue vacu...,Muy agradecidos por la invitación de Giorgia M...,VOX España,2019-10-03T11:58:23Z,inmigracion,2019
25,JG4dF-uZVlM,Lo que no vemos en el debate sobre la inmigrac...,Según la ONU en 2017 había en el mundo más de ...,TEDx Talks,2019-06-05T15:43:06Z,inmigracion,2019
26,pluhqdFuJTg,Los migrantes ilegales cometen delincuencia en...,Suscribete.,JMP Noticias TV,2019-09-20T22:04:38Z,inmigracion,2019
27,HdWUrqSey94,El vídeo que los progres y las mafias de la in...,El sentido común ha llegado al templo de la co...,VOX España,2019-09-01T20:42:51Z,inmigracion,2019
28,_FXVBcXTd0E,Cooperación contra la inmigración irregular en...,Ya ha comenzado la sustitución de las concerti...,euronews (en español),2019-11-28T15:30:39Z,inmigracion,2019
29,-hlNOQ1_qPk,Inmigración en España,Cuando los recursos naturales de un país no so...,Política de Rafael Montoto,2019-08-31T10:49:36Z,inmigracion,2019
30,RT_sjBwyUAg,Cooperación contra la inmigración irregular en...,Ya ha comenzado la sustitución de las concerti...,euronews (en español),2019-11-28T15:34:00Z,inmigracion,2019
31,w1Cke4wrROM,El drama de ser menor migrante en busca de un ...,"Abdellatif Laqiasse llegó a España solo, siend...",laSexta,2019-02-05T20:01:27Z,inmigracion,2019
32,pvd2ZO4P6sc,Opciones de inmigración para ESPAÑOLES - Viv...,Para mayor información puede escribirnos: http...,BELTRAN BRITO LLP,2019-12-04T14:12:41Z,inmigracion,2019
33,gJFiG19-j8o,"La población de EUROPA, de ESPAÑA y las MIGRAC...",Cómo son la población de Europa y España? ¿Cre...,La cuna de Halicarnaso,2019-10-28T19:34:32Z,inmigracion,2019
34,zAzvdAU1RY0,La dictadura franquista a ojos de la comunidad...,La renovación del gobierno franquista tenía un...,DMAX España,2019-06-05T16:19:21Z,inmigracion,2019
35,5x9eA0NcLa0,Bruno Navarro - La inmigración ilegal se dispa...,"08/ENE/2018 Noticias de Intereconomía TV - ""El...",Bruno Navarro,2019-01-10T08:21:09Z,inmigracion,2019
36,oyiIRZeKymA,¿Funcionan las vallas para detener la inmigrac...,We need to rethink borders and walls as we are...,TEDx Talks,2019-05-08T21:25:10Z,inmigracion,2019
37,C5vcO5PvHro,Concluye el Seminario sobre las Actitudes haci...,Organizado por el CEMyRI ha contado con la par...,Universidad de Almería,2019-05-17T12:15:18Z,inmigracion,2019
38,AZdY-ZhYTJA,Seguimiento de inmigrantes viajando a España,,GameCoolSport,2019-08-24T13:26:50Z,inmigracion,2019
39,RomI4fYPJR4,En 2019 la inmigración irregular se ha reducid...,Se contempla un aumento en las llegadas por ví...,RTVCE,2019-12-30T12:41:53Z,inmigracion,2019
40,WdHeNQHl2yM,El suma y sigue de la inmigración ilegal en Es...,Suscríbete a nuestro nuevo canal ↙ ✓ https://w...,La Toroteca,2019-01-23T07:54:10Z,inmigracion,2019
41,ne0Tf_-jaNs,Inmigración en España y en Europa,Inmigración en España y en Europa Euroconexión...,UNED Radio,2019-02-28T08:41:32Z,inmigracion,2019
42,RC0ebokxzb8,EL PROBLEMA DE LA INMIGRACIÓN EN ESPAÑA,Conferencia de Alberto Martín en las 13 Jornad...,Luis Martin,2019-10-27T19:57:18Z,inmigracion,2019
43,cK87YmZTko0,Inmigrantes africanos ilegales se toman aeropu...,,Actualidad Chile,2019-05-20T20:05:54Z,inmigracion,2019
44,loe69BCnEcA,Cuando la emigración preocupa más que la inmig...,Un estudio reciente demuestra que en algunos p...,euronews (en español),2019-04-01T16:30:23Z,inmigracion,2019
45,ywKPi1AIyWc,¿Qué sabes de los niños refugiados?,Aquí te resumimos los principales datos public...,ACNUR Comité español,2019-09-05T10:00:17Z,inmigracion,2019
46,S6dU0qaiuPk,El problema de la inmigración ilegal y el aume...,Suscríbete a nuestro nuevo canal ↙ ✓ https://w...,La Toroteca,2019-02-15T01:42:13Z,inmigracion,2019
47,LCo3yexvc00,"Los países de la Unión Europea, ¿a favor de la...",Suscríbete a nuestro nuevo canal ↙ ✓ https://w...,La Toroteca,2019-05-14T11:16:14Z,inmigracion,2019
48,6rm3x9plIcM,¡El emotivo video de una madre inmigrante y tr...,El emotivo video de una madre inmigrante y tra...,Union Law Group,2019-08-15T00:21:25Z,inmigracion,2019
49,HecY4qlt394,Inmigración en España por José María Ruiz Puerta,Fragmento del programa televisivo El Gato al A...,José María Ruiz Puerta,2019-02-13T10:01:47Z,inmigracion,2019

In [8]:
df_videos_2019.shape

(50, 7)

In [9]:
df_videos_2019[
    ['fecha_publicacion', 'canal', 'titulo']
].head(20)

,fecha_publicacion,canal,titulo
0,2019-11-09T22:45:00Z,El Toro TV,¿Inmigrantes hispanoamericanos o magrebíes?
1,2019-04-03T10:58:49Z,Política en 3 minutos,INMIGRACIÓN en España en 3 minutos
2,2019-07-22T18:57:24Z,Españoles de Cuba,Abascal : “En VOX privilegiamos la inmigración...
3,2019-01-01T13:17:05Z,euronews (en español),La policía española halla personas escondidas ...
4,2019-06-19T09:50:39Z,euronews (en español),España ya no es la principal entrada de inmigr...
5,2019-12-18T11:47:20Z,El Toro TV,Más de 30.000 inmigrantes ilegales en 2019: la...
6,2019-11-07T11:56:17Z,Cadena SER,Las mentiras de Vox sobre inmigración
7,2019-07-28T09:43:16Z,DISTRITOTV,JUAN SOLAECHE:La mayoría de la inmigración ile...
8,2019-07-11T19:13:40Z,Santiago Millan,DEBATE INMIGRACIÓN EN ESPAÑA
9,2019-12-26T11:37:30Z,laSexta,"España, un país de migrantes: los años en los ..."
10,2019-04-11T11:43:20Z,La Toroteca,"La inmigración ilegal, desbordada en España"
11,2019-01-10T14:16:36Z,La Toroteca,El gran problema del que nadie quiere hablar e...
12,2019-08-05T19:20:03Z,VOX España,Santiago Abascal denuncia en el Congreso la pa...
13,2019-09-07T18:44:43Z,FaroTV Ceuta,"“¡España, España!, ¡el Estrecho!”: el grito ma..."
14,2019-08-13T19:51:57Z,La Nicoteca,🔴🔴🔴 OPEN ARMS y la Inmigración ilegal en ESPAÑ...
15,2019-05-28T15:26:06Z,DMAX España,Así era la situación de España justo después d...
16,2019-01-03T02:01:24Z,Teletrece,Inmigrantes querían cruzar frontera en España ...
17,2019-07-04T16:58:18Z,BBC News Mundo,Valla de Melilla: la peligrosa frontera que se...
18,2019-04-09T07:44:12Z,bichopedia,"Santiago Abascal, entrevista 1ª parte: La unid..."
19,2019-10-30T12:23:40Z,Rugetistas RUGE,&quot;Cuando los españoles emigraban lo hacían...

In [10]:
video_ids = df_videos_2019["video_id"].tolist()

request_stats = youtube.videos().list(
    part="statistics",
    id=",".join(video_ids)
)

response_stats = request_stats.execute()

In [11]:
estadisticas = []

for item in response_stats["items"]:
    stats = item.get("statistics", {})

    estadisticas.append({
        "video_id": item["id"],
        "visualizaciones": int(stats.get("viewCount", 0)),
        "likes": int(stats.get("likeCount", 0)),
        "comentarios": int(stats.get("commentCount", 0))
    })

df_stats = pd.DataFrame(estadisticas)

In [12]:
df_videos_2019 = df_videos_2019.merge(
    df_stats,
    on="video_id",
    how="left"
)

In [13]:
df_videos_2019[
    [
        "video_id",
        "canal",
        "titulo",
        "visualizaciones",
        "comentarios"
    ]
].sort_values(
    "comentarios",
    ascending=False
).head(20)

,video_id,canal,titulo,visualizaciones,comentarios
15,EemzZxSxdlI,DMAX España,Así era la situación de España justo después d...,3003645,8553
34,zAzvdAU1RY0,DMAX España,La dictadura franquista a ojos de la comunidad...,2903238,7887
17,ntc0kC9lI6A,BBC News Mundo,Valla de Melilla: la peligrosa frontera que se...,2529055,6313
27,HdWUrqSey94,VOX España,El vídeo que los progres y las mafias de la in...,431421,3280
3,xF6IDLsIv_k,euronews (en español),La policía española halla personas escondidas ...,16873612,2871
12,FiLIU2dpegQ,VOX España,Santiago Abascal denuncia en el Congreso la pa...,277219,2001
0,ne7WoOWstvg,El Toro TV,¿Inmigrantes hispanoamericanos o magrebíes?,74670,1177
6,IurbEiV8xjU,Cadena SER,Las mentiras de Vox sobre inmigración,61895,877
24,y-VAW93LWOg,VOX España,Santiago Abascal en Roma &quot;España fue vacu...,87049,661
23,9-f4bcPDojU,laSexta,El papa Francisco reflexiona sobre inmigración...,392413,633
1,oiX9Hou3hEY,Política en 3 minutos,INMIGRACIÓN en España en 3 minutos,51025,260
25,JG4dF-uZVlM,TEDx Talks,Lo que no vemos en el debate sobre la inmigrac...,114963,246
32,pvd2ZO4P6sc,BELTRAN BRITO LLP,Opciones de inmigración para ESPAÑOLES - Viv...,57934,101
46,S6dU0qaiuPk,La Toroteca,El problema de la inmigración ilegal y el aume...,8367,83
9,GGQgDxjb8xQ,laSexta,"España, un país de migrantes: los años en los ...",7433,73
33,gJFiG19-j8o,La cuna de Halicarnaso,"La población de EUROPA, de ESPAÑA y las MIGRAC...",69087,72
11,4OuThKoZytQ,La Toroteca,El gran problema del que nadie quiere hablar e...,10623,70
31,w1Cke4wrROM,laSexta,El drama de ser menor migrante en busca de un ...,15707,58
2,Y5vVL5EFhCk,Españoles de Cuba,Abascal : “En VOX privilegiamos la inmigración...,7545,49
13,KA6NP4VoycU,FaroTV Ceuta,"“¡España, España!, ¡el Estrecho!”: el grito ma...",30221,47

In [14]:
pd.set_option("display.max_colwidth", None)

df_videos_2019[
    ["video_id", "canal", "titulo", "descripcion", "comentarios"]
].sort_values(
    "comentarios",
    ascending=False
)

,video_id,canal,titulo,descripcion,comentarios
15,EemzZxSxdlI,DMAX España,Así era la situación de España justo después de la guerra | España después de la Guerra,"Al terminar la Guerra Civil, España no estaba en condiciones de participar en la contienda que estallaba en el resto de Europa.",8553
34,zAzvdAU1RY0,DMAX España,La dictadura franquista a ojos de la comunidad internacional | España después de la Guerra,"La renovación del gobierno franquista tenía una intencionalidad muy marcada, abrirse al mundo. Pese a tomar medidas que ...",7887
17,ntc0kC9lI6A,BBC News Mundo,Valla de Melilla: la peligrosa frontera que separa la UE de África,Suscríbete a BBC Mundo http://vid.io/xqOx Melilla y Ceuta son dos ciudades españolas situadas en el norte de África que ...,6313
27,HdWUrqSey94,VOX España,El vídeo que los progres y las mafias de la inmigración no quieren que veas,"El sentido común ha llegado al templo de la corrección política Que se preparen los progres, esto solo acaba de empezar. Nuevo ...",3280
3,xF6IDLsIv_k,euronews (en español),La policía española halla personas escondidas en colchones para cruzar clandestinamente la frontera,El uso de colchones para esconder migrantes podría ser la nueva treta de las mafias en la frontera de Melilla.… MÁS ...,2871
12,FiLIU2dpegQ,VOX España,Santiago Abascal denuncia en el Congreso la pasividad con la inmigración masiva.,Santiago Abascal denuncia en el Congreso las políticas de puertas abiertas que las élites nos imponen a la fuerza para construir ...,2001
0,ne7WoOWstvg,El Toro TV,¿Inmigrantes hispanoamericanos o magrebíes?,El sociólogo Amando de Miguel asegura que en España no hay una política migratoria que establezca un movimiento de ...,1177
6,IurbEiV8xjU,Cadena SER,Las mentiras de Vox sobre inmigración,El partido de Santiago Abascal también miente al hablar de la inmigración y del coste económico de los inmigrantes.,877
24,y-VAW93LWOg,VOX España,Santiago Abascal en Roma &quot;España fue vacunada contra la inmigración islámica&quot;,"Muy agradecidos por la invitación de Giorgia Meloni a la convención #Atreju19 del partido italiano Fratelli d´ItaIia, aliados de VOX ...",661
23,9-f4bcPDojU,laSexta,El papa Francisco reflexiona sobre inmigración con una concertina en la mano - Salvados,Todos lo capítulos completos de 'Salvados' en Atreplayer: https://www.atresplayer.com/lasexta/programas/salvados/ Suscríbete a ...,633
1,oiX9Hou3hEY,Política en 3 minutos,INMIGRACIÓN en España en 3 minutos,La inmigración en España ha sido usada como arma arrojadiza durante muchos años por diferentes partidos políticos. En este ...,260
25,JG4dF-uZVlM,TEDx Talks,Lo que no vemos en el debate sobre la inmigración | Sani Ladan | TEDxTarragona,Según la ONU en 2017 había en el mundo más de 250 millones de personas migrantes. Migraciones que en muchos casos se ...,246
32,pvd2ZO4P6sc,BELTRAN BRITO LLP,Opciones de inmigración para ESPAÑOLES - Vivir y Trabajar en Estados Unidos,Para mayor información puede escribirnos: http://beltranbrito.com/es/contacto/ Seguirnos en Instagram: ...,101
46,S6dU0qaiuPk,La Toroteca,El problema de la inmigración ilegal y el aumento de delitos España,Suscríbete a nuestro nuevo canal ↙ ✓ https://www.youtube.com/channel/UC2T6NU6-JLWzAzaGdqvNyzA Según los datos del ...,83
9,GGQgDxjb8xQ,laSexta,"España, un país de migrantes: los años en los que estábamos en la otra cara de la moneda","Andrea Ropero recuerda en el Intermedio cuando España era un país de migrantes. Marta, ecuatoriana, y Faustina, española, ...",73
33,gJFiG19-j8o,La cuna de Halicarnaso,"La población de EUROPA, de ESPAÑA y las MIGRACIONES 🇪🇸🧳",Cómo son la población de Europa y España? ¿Crece o no crece? ¿Cómo son sus índices de natalidad y mortalidad?,72
11,4OuThKoZytQ,La Toroteca,El gran problema del que nadie quiere hablar en España: la inmigración,Suscríbete a nuestro nuevo canal ↙ ✓ https://www.youtube.com/channel/UC2T6NU6-JLWzAzaGdqvNyzA Las primeras cifras ...,70
31,w1Cke4wrROM,laSexta,El drama de ser menor migrante en busca de un futuro en España,"Abdellatif Laqiasse llegó a España solo, siendo menor de edad y sin saber el idioma, ahora, es educador social. Gonzo le ...",58
2,Y5vVL5EFhCk,Españoles de Cuba,Abascal : “En VOX privilegiamos la inmigración hispanoamericana&quot;,Abascal : “En VOX privilegiamos la inmigración hispanoamericana para solucionar lo problemas de España y de Europa”,49
13,KA6NP4VoycU,FaroTV Ceuta,"“¡España, España!, ¡el Estrecho!”: el grito marroquí de la inmigración","En trajes de neopreno, en kayak o, los que pueden, en embarcaciones algo más preparadas. Es la escapada de jóvenes ...",47
21,fyAlQMdBkjo,euronews (en español),Los chalecos negros piden papeles para los inmigrantes,Los chalecos negros piden papeles para los inmigrantes … MÁS INFORMACIÓN ...,45
16,3VmBYcMcLRU,Teletrece,Inmigrantes querían cruzar frontera en España dentro de un colchón,Más informaciones en » http://T13.cl Síguenos en nuestras redes sociales: Facebook https://www.facebook.com/pg/teletrece ...,40
4,-Gytamy7G2E,euronews (en español),España ya no es la principal entrada de inmigrantes irregulares en la UE,"Según el ministerio del Interior, las llegadas al país por mar se han reducido en 2019 casi un 20% con respecto al mismo periodo ...",26
22,Km3Heq7tnFw,euronews (en español),España pide a la UE más ayudas para Marruecos en su lucha contra la inmigración ilegal,"Marruecos ha hecho su parte, la Unión Europea debe hacer la suya. Es lo que ha venido a decir el ministro español de Exteriores ...",25
40,WdHeNQHl2yM,La Toroteca,El suma y sigue de la inmigración ilegal en España,"Suscríbete a nuestro nuevo canal ↙ ✓ https://www.youtube.com/channel/UC2T6NU6-JLWzAzaGdqvNyzA Según el informe, ...",25
14,RuWO0NTPZus,La Nicoteca,🔴🔴🔴 OPEN ARMS y la Inmigración ilegal en ESPAÑA ( entre otros temas)- La Nicoteca,"Buenos días señoras y sñores! Hoy vamos a hablar sobre el OPEN ARMS, RICHARD GERE y la implicación del OPEN ARMS en ...",17
43,cK87YmZTko0,Actualidad Chile,Inmigrantes africanos ilegales se toman aeropuerto Charles de Gaulle en París,,14
47,LCo3yexvc00,La Toroteca,"Los países de la Unión Europea, ¿a favor de la inmigración?",Suscríbete a nuestro nuevo canal ↙ ✓ https://www.youtube.com/channel/UC2T6NU6-JLWzAzaGdqvNyzA ¿Quieren la mayoría ...,14
10,Z5YzLgXEjg4,La Toroteca,"La inmigración ilegal, desbordada en España","Suscríbete a nuestro nuevo canal ↙ ✓ https://www.youtube.com/channel/UC2T6NU6-JLWzAzaGdqvNyzA Al ritmo actual, en 30 ...",14
5,-ardA7cU6f0,El Toro TV,Más de 30.000 inmigrantes ilegales en 2019: la radiografía de la inmigración ilegal en España,Cuántos inmigrantes irregulares han entrado en nuestro país en el último año? ¿Cuál es la ruta más usada por este tipo de ...,9
36,oyiIRZeKymA,TEDx Talks,¿Funcionan las vallas para detener la inmigración? | Dani Villanueva | TEDxVitoriaGasteiz,We need to rethink borders and walls as we are creating them today. The number of kilometers of walls and artificial borders has ...,8
30,RT_sjBwyUAg,euronews (en español),Cooperación contra la inmigración irregular entre Marruecos y España,"Ya ha comenzado la sustitución de las concertinas de la valla de Melilla por ""elementos más seguros y menos cruentos""…",7
44,loe69BCnEcA,euronews (en español),Cuando la emigración preocupa más que la inmigración,Un estudio reciente demuestra que en algunos países de la Unión Europea preocupa más la fuga de cerebros que la llegada de ...,6
7,PUKFLX0T-iM,DISTRITOTV,JUAN SOLAECHE:La mayoría de la inmigración ilegal en España entran como turistas,"Distrito Televisión es un canal de televisión que incluye información política, económica, deportiva y social, películas, series y ...",5
49,HecY4qlt394,José María Ruiz Puerta,Inmigración en España por José María Ruiz Puerta,Fragmento del programa televisivo El Gato al Agua emitido el día 29 de enero 2019. José María Ruiz Puerta analiza la ...,3
28,_FXVBcXTd0E,euronews (en español),Cooperación contra la inmigración irregular entre Marruecos y España,"Ya ha comenzado la sustitución de las concertinas de la valla de Melilla por ""elementos más seguros y menos cruentos""…",3
35,5x9eA0NcLa0,Bruno Navarro,Bruno Navarro - La inmigración ilegal se dispara en España,"08/ENE/2018 Noticias de Intereconomía TV - ""El Mundo en Guerra"" Repasamos las escalofriantes cifras de llegadas en 2018, las ...",2
19,P3CFqc1PVlU,Rugetistas RUGE,&quot;Cuando los españoles emigraban lo hacían con papeles&quot;,Probablemente habrás escuchado muchas veces esta frase. Es mentira.,1
26,pluhqdFuJTg,JMP Noticias TV,Los migrantes ilegales cometen delincuencia en el Mundo. España es un ejemplo.,Suscribete.,1
8,8tLCJ6Q-hNc,Santiago Millan,DEBATE INMIGRACIÓN EN ESPAÑA,,0
20,c0GGvFBMNsI,AGENCIA EFE,Los ecos de la inmigración española en Bélgica,"Bruselas (Bélgica), 19 jun (EFE).- (Imagen: Ana Belinchón/Leo Rodríguez) La iglesia de Jesús Trabajador, en el barrio ...",0
18,8PwWreXU3vU,bichopedia,"Santiago Abascal, entrevista 1ª parte: La unidad de España, la inmigración","Qué es España para Santiago Abascal?, ¿cuál es la posición de VOX respecto a la inmigración? A estas preguntas y otras ...",0
29,-hlNOQ1_qPk,Política de Rafael Montoto,Inmigración en España,"Cuando los recursos naturales de un país no son suficientes para mantener a su población, ésta se ve obligada a emigrar a otros ...",0
39,RomI4fYPJR4,RTVCE,"En 2019 la inmigración irregular se ha reducido un 50,5% en España","Se contempla un aumento en las llegadas por vía marítima de un 25%, es decir, 116 inmigrantes más que en 2018. Por vía ...",0
38,AZdY-ZhYTJA,GameCoolSport,Seguimiento de inmigrantes viajando a España,,0
37,C5vcO5PvHro,Universidad de Almería,Concluye el Seminario sobre las Actitudes hacia la Inmigración en España,Organizado por el CEMyRI ha contado con la participación de expertos en el tema. Los datos de las encuestan aseguran que la ...,0
41,ne0Tf_-jaNs,UNED Radio,Inmigración en España y en Europa,Inmigración en España y en Europa Euroconexión. Elecciones al Parlamento Europeo 2019 Serie: Euroconexión Fecha de ...,0
42,RC0ebokxzb8,Luis Martin,EL PROBLEMA DE LA INMIGRACIÓN EN ESPAÑA,Conferencia de Alberto Martín en las 13 Jornadas de la Synthèse Nationale (París - octubre 2019) ACIMJI Asociación Cultural In ...,0
45,ywKPi1AIyWc,ACNUR Comité español,¿Qué sabes de los niños refugiados?,Aquí te resumimos los principales datos publicados por el Informe de Tendencias Globales 2018.,0
48,6rm3x9plIcM,Union Law Group,¡El emotivo video de una madre inmigrante y trabajadora!,El emotivo video de una madre inmigrante y trabajadora! Quien gracias al esfuerzo y constante busqueda de ayuda de sus ...,0

In [15]:
videos_validos_2019 = df_videos_2019[
    ~df_videos_2019["video_id"].isin([
        "EemzZxSxdlI",  # Posguerra
        "zAzvdAU1RY0"   # Dictadura franquista
    ])
].copy()

In [16]:
videos_validos_2019 = videos_validos_2019[
    videos_validos_2019["comentarios"] >= 20
].copy()

videos_validos_2019.shape

(23, 10)

In [17]:
videos_piloto = (
    videos_validos_2019
    .sort_values("comentarios", ascending=False)
    .head(5)
)

videos_piloto[
    ["video_id", "canal", "titulo", "comentarios"]
]

,video_id,canal,titulo,comentarios
17,ntc0kC9lI6A,BBC News Mundo,Valla de Melilla: la peligrosa frontera que separa la UE de África,6313
27,HdWUrqSey94,VOX España,El vídeo que los progres y las mafias de la inmigración no quieren que veas,3280
3,xF6IDLsIv_k,euronews (en español),La policía española halla personas escondidas en colchones para cruzar clandestinamente la frontera,2871
12,FiLIU2dpegQ,VOX España,Santiago Abascal denuncia en el Congreso la pasividad con la inmigración masiva.,2001
0,ne7WoOWstvg,El Toro TV,¿Inmigrantes hispanoamericanos o magrebíes?,1177

In [18]:
comentarios = []

video_id = "ntc0kC9lI6A"

request = youtube.commentThreads().list(
    part="snippet",
    videoId=video_id,
    maxResults=100,
    textFormat="plainText"
)

response = request.execute()

for item in response["items"]:

    comentario = item["snippet"]["topLevelComment"]["snippet"]

    comentarios.append({
        "video_id": video_id,
        "autor": comentario["authorDisplayName"],
        "fecha": comentario["publishedAt"],
        "likes": comentario["likeCount"],
        "texto": comentario["textDisplay"]
    })

df_comentarios = pd.DataFrame(comentarios)

df_comentarios.head()

,video_id,autor,fecha,likes,texto
0,ntc0kC9lI6A,@mariolujano9065,2026-07-05T19:31:23Z,0,"Pero luego llegan a cruzar y en vez de trabajar y prosperar, se ponen a delinquir y adesobedecwr las leyes y asi en ningun lado los quieren."
1,ntc0kC9lI6A,@NaNa-q9b3o,2026-06-11T07:32:29Z,0,إذا لم تفكيك ذالك السياج أيها الشاذ جنسيا نحن لدينا مجلس شيوخ وبيت أبيض خاص بنا ولا نريد إسستخدام القوة ما لا نطيق
2,ntc0kC9lI6A,@china2221,2026-06-01T14:14:52Z,0,El precio por robar territorio Africano. Eso no es Europa. No pertenece a España ni Inglaterra.
3,ntc0kC9lI6A,@MariaHwhshd-s4b,2026-05-25T08:36:59Z,0,Dejar de hipócritas quien quiera ayudar me parece muy digno pero que lo hagan con sus propios medios.
4,ntc0kC9lI6A,@hornachos,2026-05-16T14:50:32Z,0,LAS ONG SON MAFIAS QUE SE LUCRAN

In [19]:
df_comentarios.shape

(100, 5)

In [20]:
def extraer_comentarios_video(youtube, video_id, max_comentarios=1000):

    comentarios = []
    page_token = None

    while len(comentarios) < max_comentarios:

        request = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            maxResults=100,
            textFormat="plainText",
            pageToken=page_token,
            order="relevance"
        )

        response = request.execute()

        for item in response["items"]:

            comentario = item["snippet"]["topLevelComment"]["snippet"]

            comentarios.append({
                "video_id": video_id,
                "autor": comentario["authorDisplayName"],
                "fecha": comentario["publishedAt"],
                "likes": comentario["likeCount"],
                "texto": comentario["textDisplay"]
            })

            if len(comentarios) >= max_comentarios:
                break

        page_token = response.get("nextPageToken")

        if not page_token:
            break

    return pd.DataFrame(comentarios)

In [21]:
df_comentarios_bbc = extraer_comentarios_video(
    youtube=youtube,
    video_id="ntc0kC9lI6A",
    max_comentarios=7000
)

df_comentarios_bbc["fecha"] = pd.to_datetime(
    df_comentarios_bbc["fecha"]
)

df_comentarios_bbc["fecha"].dt.year.value_counts().sort_index()

fecha
2019    110
2020     65
2021    339
2022    350
2023     14
2024     14
2025      8
2026      7
Name: count, dtype: int64

In [22]:
df_comentarios_bbc["fecha"] = pd.to_datetime(
    df_comentarios_bbc["fecha"]
)

In [23]:
df_comentarios_bbc["fecha"].dt.year.value_counts().sort_index()

fecha
2019    110
2020     65
2021    339
2022    350
2023     14
2024     14
2025      8
2026      7
Name: count, dtype: int64

## ------

In [26]:
todos_comentarios_2019 = []

for _, video in tqdm(
    df_videos_2019.iterrows(),
    total=len(df_videos_2019)
):

    video_id = video["video_id"]

    try:
        df_temp = extraer_comentarios_video(
            youtube=youtube,
            video_id=video_id,
            max_comentarios=1000
        )

        if not df_temp.empty:
            df_temp["titulo_video"] = video["titulo"]
            df_temp["canal"] = video["canal"]
            df_temp["fecha_video"] = video["fecha_publicacion"]
            df_temp["año_video"] = 2019
            df_temp["tema"] = "inmigracion"

            todos_comentarios_2019.append(df_temp)

        time.sleep(0.2)

    except Exception as e:
        print(f"Error en {video_id}: {e}")

 76%|███████▌  | 38/50 [00:34<00:07,  1.71it/s]

Error en C5vcO5PvHro: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=C5vcO5PvHro&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

100%|██████████| 50/50 [00:38<00:00,  1.31it/s]

In [27]:
df_youtube_2019 = pd.concat(
    todos_comentarios_2019,
    ignore_index=True
)

df_youtube_2019.shape

(7007, 10)

In [28]:
df_youtube_2019["fecha"] = pd.to_datetime(
    df_youtube_2019["fecha"]
)

df_youtube_2019["fecha_video"] = pd.to_datetime(
    df_youtube_2019["fecha_video"]
)

In [29]:
df_youtube_2019["fecha"].dt.year.value_counts().sort_index()

fecha
2019    2682
2020     689
2021    1342
2022    1200
2023     270
2024     322
2025     412
2026      90
Name: count, dtype: int64

In [30]:
df_youtube_2019["video_id"].nunique()

39

In [31]:
df_youtube_2019["fecha"] = pd.to_datetime(
    df_youtube_2019["fecha"]
)

df_youtube_2019["fecha"].dt.year.value_counts().sort_index()

fecha
2019    2682
2020     689
2021    1342
2022    1200
2023     270
2024     322
2025     412
2026      90
Name: count, dtype: int64

In [32]:
df_youtube_2019.groupby(
    "canal"
).size().sort_values(
    ascending=False
).head(20)

canal
VOX España                2373
DMAX España               1571
euronews (en español)     1039
BBC News Mundo             907
Cadena SER                 257
laSexta                    232
El Toro TV                 167
TEDx Talks                 139
Política en 3 minutos       86
La Toroteca                 62
La cuna de Halicarnaso      54
BELTRAN BRITO LLP           33
FaroTV Ceuta                28
Españoles de Cuba           19
Teletrece                   13
La Nicoteca                 12
Actualidad Chile             7
DISTRITOTV                   3
José María Ruiz Puerta       2
Bruno Navarro                1
dtype: int64

In [33]:
df_youtube_2019["video_id"].nunique()

39

In [ ]:
from pathlib import Path

df_youtube_2019.to_csv(
    RUTA_RAW / "youtube_inmigracion_2019_comentarios.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Archivo guardado correctamente")

Archivo guardado correctamente

# 1. Buscar vídeos

In [ ]:
# ==================================================
# YOUTUBE - INMIGRACIÓN - 2015
# ==================================================

request = youtube.search().list(
    part="snippet",
    q="inmigración España",
    type="video",
    maxResults=50,
    relevanceLanguage="es",
    regionCode="ES",
    publishedAfter="2015-01-01T00:00:00Z",
    publishedBefore="2016-01-01T00:00:00Z",
    order="relevance"
)

response_2015 = request.execute()

# 2. Crear Dataframe de vídeos

In [ ]:
videos_2015 = []

for item in response_2015["items"]:
    videos_2015.append({
        "video_id": item["id"]["videoId"],
        "titulo": item["snippet"]["title"],
        "descripcion": item["snippet"]["description"],
        "canal": item["snippet"]["channelTitle"],
        "fecha_publicacion": item["snippet"]["publishedAt"],
        "tema_busqueda": "inmigracion",
        "año_busqueda": 2015
    })

df_videos_2015 = pd.DataFrame(videos_2015)

# 3. Obtener estadísticas

In [ ]:
video_ids = df_videos_2015["video_id"].tolist()

request_stats = youtube.videos().list(
    part="statistics",
    id=",".join(video_ids)
)

response_stats = request_stats.execute()

# 4. Creat dataframe de estadísticas

In [ ]:
estadisticas = []

for item in response_stats["items"]:

    stats = item.get("statistics", {})

    estadisticas.append({
        "video_id": item["id"],
        "visualizaciones": int(stats.get("viewCount", 0)),
        "likes": int(stats.get("likeCount", 0)),
        "comentarios": int(stats.get("commentCount", 0))
    })

df_stats = pd.DataFrame(estadisticas)

# 5. Unir vídeos y estadísticas

In [ ]:
df_videos_2015 = df_videos_2015.merge(
    df_stats,
    on="video_id",
    how="left"
)

df_videos_2015.shape

(50, 10)

# 6. Extraer comentarios de los 50 vídeos

In [ ]:
todos_comentarios_2015 = []

for _, video in tqdm(
    df_videos_2015.iterrows(),
    total=len(df_videos_2015)
):

    video_id = video["video_id"]

    try:

        df_temp = extraer_comentarios_video(
            youtube=youtube,
            video_id=video_id,
            max_comentarios=1000
        )

        if not df_temp.empty:

            df_temp["titulo_video"] = video["titulo"]
            df_temp["canal"] = video["canal"]
            df_temp["fecha_video"] = video["fecha_publicacion"]
            df_temp["año_video"] = 2015
            df_temp["tema"] = "inmigracion"

            todos_comentarios_2015.append(df_temp)

        time.sleep(0.2)

    except Exception as e:

        print(f"Error en {video_id}: {e}")

 84%|████████▍ | 42/50 [00:15<00:01,  5.25it/s]

Error en 8PwyexEdmGs: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=8PwyexEdmGs&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Error en 0fzTYyELJsY: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=0fzTYyELJsY&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

100%|██████████| 50/50 [00:17<00:00,  2.78it/s]

# 7. Unir comentarios

In [ ]:
df_youtube_2015 = pd.concat(
    todos_comentarios_2015,
    ignore_index=True
)

df_youtube_2015.shape

(817, 10)

# 8. Convertir fechas

In [ ]:
df_youtube_2015["fecha"] = pd.to_datetime(
    df_youtube_2015["fecha"]
)

df_youtube_2015["fecha_video"] = pd.to_datetime(
    df_youtube_2015["fecha_video"]
)

# 9. Comprobar distribución temporal

In [ ]:
df_youtube_2015["fecha"].dt.year.value_counts().sort_index()

fecha
2015     21
2016     33
2017     23
2018     58
2019    158
2020    121
2021    110
2022     84
2023     65
2024     63
2025     55
2026     26
Name: count, dtype: int64

# 10. Guardar CSV

In [ ]:
df_youtube_2015.to_csv(
    RUTA_RAW / "youtube_inmigracion_2015_comentarios.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Archivo guardado")

Archivo guardado

# 1. Buscar vídeos

In [ ]:
# ==================================================
# YOUTUBE - INMIGRACIÓN - 2016
# ==================================================

request = youtube.search().list(
    part="snippet",
    q="inmigración España",
    type="video",
    maxResults=50,
    relevanceLanguage="es",
    regionCode="ES",
    publishedAfter="2016-01-01T00:00:00Z",
    publishedBefore="2017-01-01T00:00:00Z",
    order="relevance"
)

response_2016 = request.execute()

# 2. Crear Dataframe de vídeos

In [ ]:
videos_2016 = []

for item in response_2016["items"]:
    videos_2016.append({
        "video_id": item["id"]["videoId"],
        "titulo": item["snippet"]["title"],
        "descripcion": item["snippet"]["description"],
        "canal": item["snippet"]["channelTitle"],
        "fecha_publicacion": item["snippet"]["publishedAt"],
        "tema_busqueda": "inmigracion",
        "año_busqueda": 2016
    })

df_videos_2016 = pd.DataFrame(videos_2016)

# 3. Obtener estadísticas

In [ ]:
video_ids = df_videos_2016["video_id"].tolist()

request_stats = youtube.videos().list(
    part="statistics",
    id=",".join(video_ids)
)

response_stats = request_stats.execute()

# 4. Creat dataframe de estadísticas

In [ ]:
estadisticas = []

for item in response_stats["items"]:

    stats = item.get("statistics", {})

    estadisticas.append({
        "video_id": item["id"],
        "visualizaciones": int(stats.get("viewCount", 0)),
        "likes": int(stats.get("likeCount", 0)),
        "comentarios": int(stats.get("commentCount", 0))
    })

df_stats = pd.DataFrame(estadisticas)

# 5. Unir vídeos y estadísticas

In [ ]:
df_videos_2016 = df_videos_2016.merge(
    df_stats,
    on="video_id",
    how="left"
)

df_videos_2016.shape

(50, 10)

# 6. Extraer comentarios de los 50 vídeos

In [ ]:
todos_comentarios_2016 = []

for _, video in tqdm(
    df_videos_2016.iterrows(),
    total=len(df_videos_2016)
):

    video_id = video["video_id"]

    try:

        df_temp = extraer_comentarios_video(
            youtube=youtube,
            video_id=video_id,
            max_comentarios=1000
        )

        if not df_temp.empty:

            df_temp["titulo_video"] = video["titulo"]
            df_temp["canal"] = video["canal"]
            df_temp["fecha_video"] = video["fecha_publicacion"]
            df_temp["año_video"] = 2016
            df_temp["tema"] = "inmigracion"

            todos_comentarios_2016.append(df_temp)

        time.sleep(0.2)

    except Exception as e:

        print(f"Error en {video_id}: {e}")

 52%|█████▏    | 26/50 [00:10<00:07,  3.37it/s]

Error en AlR5d2ZKRFE: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=AlR5d2ZKRFE&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

 64%|██████▍   | 32/50 [00:12<00:09,  1.85it/s]

Error en IhuVQvfFLbY: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=IhuVQvfFLbY&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

100%|██████████| 50/50 [00:22<00:00,  2.26it/s]

# 7. Unir comentarios

In [ ]:
df_youtube_2016 = pd.concat(
    todos_comentarios_2016,
    ignore_index=True
)

df_youtube_2016.shape

(2084, 10)

# 8. Convertir fechas

In [ ]:
df_youtube_2016["fecha"] = pd.to_datetime(
    df_youtube_2016["fecha"]
)

df_youtube_2016["fecha_video"] = pd.to_datetime(
    df_youtube_2016["fecha_video"]
)

# 9. Comprobar distribución temporal

In [ ]:
df_youtube_2016["fecha"].dt.year.value_counts().sort_index()

fecha
2016     76
2017    117
2018    208
2019    266
2020    318
2021     87
2022     42
2023    228
2024    360
2025    292
2026     90
Name: count, dtype: int64

# 10. Guardar CSV

In [ ]:
df_youtube_2016.to_csv(
    RUTA_RAW / "youtube_inmigracion_2016_comentarios.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Archivo guardado")

Archivo guardado

# 1. Buscar vídeos

In [ ]:
# ==================================================
# YOUTUBE - INMIGRACIÓN - 2023
# ==================================================

request = youtube.search().list(
    part="snippet",
    q="inmigración España",
    type="video",
    maxResults=50,
    relevanceLanguage="es",
    regionCode="ES",
    publishedAfter="2023-01-01T00:00:00Z",
    publishedBefore="2024-01-01T00:00:00Z",
    order="relevance"
)

response_2023 = request.execute()

# 2. Crear Dataframe de vídeos

In [ ]:
videos_2023 = []

for item in response_2023["items"]:
    videos_2023.append({
        "video_id": item["id"]["videoId"],
        "titulo": item["snippet"]["title"],
        "descripcion": item["snippet"]["description"],
        "canal": item["snippet"]["channelTitle"],
        "fecha_publicacion": item["snippet"]["publishedAt"],
        "tema_busqueda": "inmigracion",
        "año_busqueda": 2023
    })

df_videos_2023 = pd.DataFrame(videos_2023)

# 3. Obtener estadísticas

In [ ]:
video_ids = df_videos_2023["video_id"].tolist()

request_stats = youtube.videos().list(
    part="statistics",
    id=",".join(video_ids)
)

response_stats = request_stats.execute()

# 4. Creat dataframe de estadísticas

In [ ]:
estadisticas = []

for item in response_stats["items"]:

    stats = item.get("statistics", {})

    estadisticas.append({
        "video_id": item["id"],
        "visualizaciones": int(stats.get("viewCount", 0)),
        "likes": int(stats.get("likeCount", 0)),
        "comentarios": int(stats.get("commentCount", 0))
    })

df_stats = pd.DataFrame(estadisticas)

# 5. Unir vídeos y estadísticas

In [ ]:
df_videos_2023 = df_videos_2023.merge(
    df_stats,
    on="video_id",
    how="left"
)

df_videos_2023.shape

(50, 10)

# 6. Extraer comentarios de los 50 vídeos

In [ ]:
todos_comentarios_2023 = []

for _, video in tqdm(
    df_videos_2023.iterrows(),
    total=len(df_videos_2023)
):

    video_id = video["video_id"]

    try:

        df_temp = extraer_comentarios_video(
            youtube=youtube,
            video_id=video_id,
            max_comentarios=1000
        )

        if not df_temp.empty:

            df_temp["titulo_video"] = video["titulo"]
            df_temp["canal"] = video["canal"]
            df_temp["fecha_video"] = video["fecha_publicacion"]
            df_temp["año_video"] = 2023
            df_temp["tema"] = "inmigracion"

            todos_comentarios_2023.append(df_temp)

        time.sleep(0.2)

    except Exception as e:

        print(f"Error en {video_id}: {e}")

 80%|████████  | 40/50 [00:34<00:10,  1.09s/it]

Error en hQLa_MocDrE: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=hQLa_MocDrE&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

100%|██████████| 50/50 [00:44<00:00,  1.13it/s]

# 7. Unir comentarios

In [ ]:
df_youtube_2023 = pd.concat(
    todos_comentarios_2023,
    ignore_index=True
)

df_youtube_2023.shape

(7539, 10)

# 8. Convertir fechas

In [ ]:
df_youtube_2023["fecha"] = pd.to_datetime(
    df_youtube_2023["fecha"]
)

df_youtube_2023["fecha_video"] = pd.to_datetime(
    df_youtube_2023["fecha_video"]
)

# 9. Comprobar distribución temporal

In [ ]:
df_youtube_2023["fecha"].dt.year.value_counts().sort_index()

fecha
2023    3818
2024    1887
2025    1440
2026     394
Name: count, dtype: int64

# 10. Guardar CSV

In [ ]:
df_youtube_2023.to_csv(
    RUTA_RAW / "youtube_inmigracion_2023_comentarios.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Archivo guardado")

Archivo guardado

# -------------------------------------------

# LGTBI

In [ ]:
# ==================================================
# YOUTUBE - LGTBI - 2023
# ==================================================

request = youtube.search().list(
    part="snippet",
    q="LGTBI España",
    type="video",
    maxResults=50,
    relevanceLanguage="es",
    regionCode="ES",
    publishedAfter="2023-01-01T00:00:00Z",
    publishedBefore="2024-01-01T00:00:00Z",
    order="relevance"
)

response_lgtbi_2023 = request.execute()

In [ ]:
videos_lgtbi_2023 = []

for item in response_lgtbi_2023["items"]:
    videos_lgtbi_2023.append({
        "video_id": item["id"]["videoId"],
        "titulo": item["snippet"]["title"],
        "descripcion": item["snippet"]["description"],
        "canal": item["snippet"]["channelTitle"],
        "fecha_publicacion": item["snippet"]["publishedAt"],
        "tema_busqueda": "lgtbi",
        "año_busqueda": 2023
    })

df_videos_lgtbi_2023 = pd.DataFrame(videos_lgtbi_2023)

In [ ]:
video_ids = df_videos_lgtbi_2023["video_id"].tolist()

request_stats = youtube.videos().list(
    part="statistics",
    id=",".join(video_ids)
)

response_stats = request_stats.execute()

In [ ]:
estadisticas = []

for item in response_stats["items"]:

    stats = item.get("statistics", {})

    estadisticas.append({
        "video_id": item["id"],
        "visualizaciones": int(stats.get("viewCount", 0)),
        "likes": int(stats.get("likeCount", 0)),
        "comentarios": int(stats.get("commentCount", 0))
    })

df_stats = pd.DataFrame(estadisticas)

In [ ]:
todos_comentarios_lgtbi_2023 = []

for _, video in tqdm(
    df_videos_lgtbi_2023.iterrows(),
    total=len(df_videos_lgtbi_2023)
):

    video_id = video["video_id"]

    try:

        df_temp = extraer_comentarios_video(
            youtube=youtube,
            video_id=video_id,
            max_comentarios=1000
        )

        if not df_temp.empty:

            df_temp["titulo_video"] = video["titulo"]
            df_temp["canal"] = video["canal"]
            df_temp["fecha_video"] = video["fecha_publicacion"]
            df_temp["año_video"] = 2023
            df_temp["tema"] = "lgtbi"

            todos_comentarios_lgtbi_2023.append(df_temp)

        time.sleep(0.2)

    except Exception as e:

        print(f"Error en {video_id}: {e}")

 22%|██▏       | 11/50 [00:12<00:58,  1.51s/it]

Error en Sv0Y-XhukXA: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=Sv0Y-XhukXA&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

100%|██████████| 50/50 [00:35<00:00,  1.42it/s]

In [ ]:
df_youtube_lgtbi_2023 = pd.concat(
    todos_comentarios_lgtbi_2023,
    ignore_index=True
)

df_youtube_lgtbi_2023.shape

(5642, 10)

In [ ]:
df_youtube_lgtbi_2023.to_csv(
    RUTA_RAW / "youtube_lgtbi_2023_comentarios.csv",
    index=False,
    encoding="utf-8-sig"
)

In [ ]:
# ==================================================
# YOUTUBE - LGTBI - 2019
# ==================================================

request = youtube.search().list(
    part="snippet",
    q="LGTBI España",
    type="video",
    maxResults=50,
    relevanceLanguage="es",
    regionCode="ES",
    publishedAfter="2019-01-01T00:00:00Z",
    publishedBefore="2020-01-01T00:00:00Z",
    order="relevance"
)

response_lgtbi_2019 = request.execute()

In [ ]:
videos_lgtbi_2019 = []

for item in response_lgtbi_2019["items"]:
    videos_lgtbi_2019.append({
        "video_id": item["id"]["videoId"],
        "titulo": item["snippet"]["title"],
        "descripcion": item["snippet"]["description"],
        "canal": item["snippet"]["channelTitle"],
        "fecha_publicacion": item["snippet"]["publishedAt"],
        "tema_busqueda": "lgtbi",
        "año_busqueda": 2019
    })

df_videos_lgtbi_2019 = pd.DataFrame(videos_lgtbi_2019)

In [ ]:
video_ids = df_videos_lgtbi_2019["video_id"].tolist()

request_stats = youtube.videos().list(
    part="statistics",
    id=",".join(video_ids)
)

response_stats = request_stats.execute()

In [ ]:
estadisticas = []

for item in response_stats["items"]:

    stats = item.get("statistics", {})

    estadisticas.append({
        "video_id": item["id"],
        "visualizaciones": int(stats.get("viewCount", 0)),
        "likes": int(stats.get("likeCount", 0)),
        "comentarios": int(stats.get("commentCount", 0))
    })

df_stats = pd.DataFrame(estadisticas)

In [ ]:
todos_comentarios_lgtbi_2019 = []

for _, video in tqdm(
    df_videos_lgtbi_2019.iterrows(),
    total=len(df_videos_lgtbi_2019)
):

    video_id = video["video_id"]

    try:

        df_temp = extraer_comentarios_video(
            youtube=youtube,
            video_id=video_id,
            max_comentarios=1000
        )

        if not df_temp.empty:

            df_temp["titulo_video"] = video["titulo"]
            df_temp["canal"] = video["canal"]
            df_temp["fecha_video"] = video["fecha_publicacion"]
            df_temp["año_video"] = 2019
            df_temp["tema"] = "lgtbi"

            todos_comentarios_lgtbi_2019.append(df_temp)

        time.sleep(0.2)

    except Exception as e:

        print(f"Error en {video_id}: {e}")

 58%|█████▊    | 29/50 [00:28<00:06,  3.22it/s]

Error en OLmPVJwqa6c: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=OLmPVJwqa6c&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Error en dBjEJo5wpro: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=dBjEJo5wpro&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

100%|██████████| 50/50 [00:42<00:00,  1.18it/s]

In [ ]:
df_youtube_lgtbi_2019 = pd.concat(
    todos_comentarios_lgtbi_2019,
    ignore_index=True
)

df_youtube_lgtbi_2019.shape

(6469, 10)

In [ ]:
df_youtube_lgtbi_2019.to_csv(
    RUTA_RAW / "youtube_lgtbi_2019_comentarios.csv",
    index=False,
    encoding="utf-8-sig"
)

In [ ]:
# ==================================================
# YOUTUBE - LGTBI - 2016
# ==================================================

request = youtube.search().list(
    part="snippet",
    q="LGTBI España",
    type="video",
    maxResults=50,
    relevanceLanguage="es",
    regionCode="ES",
    publishedAfter="2016-01-01T00:00:00Z",
    publishedBefore="2017-01-01T00:00:00Z",
    order="relevance"
)

response_lgtbi_2016 = request.execute()

In [ ]:
videos_lgtbi_2016 = []

for item in response_lgtbi_2016["items"]:
    videos_lgtbi_2016.append({
        "video_id": item["id"]["videoId"],
        "titulo": item["snippet"]["title"],
        "descripcion": item["snippet"]["description"],
        "canal": item["snippet"]["channelTitle"],
        "fecha_publicacion": item["snippet"]["publishedAt"],
        "tema_busqueda": "lgtbi",
        "año_busqueda": 2016
    })

df_videos_lgtbi_2016 = pd.DataFrame(videos_lgtbi_2016)

In [ ]:
video_ids = df_videos_lgtbi_2016["video_id"].tolist()

request_stats = youtube.videos().list(
    part="statistics",
    id=",".join(video_ids)
)

response_stats = request_stats.execute()

In [ ]:
estadisticas = []

for item in response_stats["items"]:

    stats = item.get("statistics", {})

    estadisticas.append({
        "video_id": item["id"],
        "visualizaciones": int(stats.get("viewCount", 0)),
        "likes": int(stats.get("likeCount", 0)),
        "comentarios": int(stats.get("commentCount", 0))
    })

df_stats = pd.DataFrame(estadisticas)

In [ ]:
todos_comentarios_lgtbi_2016 = []

for _, video in tqdm(
    df_videos_lgtbi_2016.iterrows(),
    total=len(df_videos_lgtbi_2016)
):

    video_id = video["video_id"]

    try:

        df_temp = extraer_comentarios_video(
            youtube=youtube,
            video_id=video_id,
            max_comentarios=1000
        )

        if not df_temp.empty:

            df_temp["titulo_video"] = video["titulo"]
            df_temp["canal"] = video["canal"]
            df_temp["fecha_video"] = video["fecha_publicacion"]
            df_temp["año_video"] = 2016
            df_temp["tema"] = "lgtbi"

            todos_comentarios_lgtbi_2016.append(df_temp)

        time.sleep(0.2)

    except Exception as e:

        print(f"Error en {video_id}: {e}")

 38%|███▊      | 19/50 [00:18<00:13,  2.23it/s]

Error en oxmGuooz_g4: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=oxmGuooz_g4&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

 54%|█████▍    | 27/50 [00:20<00:07,  3.18it/s]

Error en NAex3s3_iC8: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=NAex3s3_iC8&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

 82%|████████▏ | 41/50 [00:30<00:05,  1.60it/s]

Error en AD2Er1kDaEM: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=AD2Er1kDaEM&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

100%|██████████| 50/50 [00:33<00:00,  1.49it/s]

In [ ]:
df_youtube_lgtbi_2016 = pd.concat(
    todos_comentarios_lgtbi_2016,
    ignore_index=True
)

df_youtube_lgtbi_2016.shape

(4791, 10)

In [ ]:
df_youtube_lgtbi_2016.to_csv(
    RUTA_RAW / "youtube_lgtbi_2016_comentarios.csv",
    index=False,
    encoding="utf-8-sig"
)

In [ ]:
# ==================================================
# YOUTUBE - LGTBI - 2015
# ==================================================

request = youtube.search().list(
    part="snippet",
    q="LGTBI España",
    type="video",
    maxResults=50,
    relevanceLanguage="es",
    regionCode="ES",
    publishedAfter="2015-01-01T00:00:00Z",
    publishedBefore="2016-01-01T00:00:00Z",
    order="relevance"
)

response_lgtbi_2015 = request.execute()

In [ ]:
videos_lgtbi_2015 = []

for item in response_lgtbi_2015["items"]:
    videos_lgtbi_2015.append({
        "video_id": item["id"]["videoId"],
        "titulo": item["snippet"]["title"],
        "descripcion": item["snippet"]["description"],
        "canal": item["snippet"]["channelTitle"],
        "fecha_publicacion": item["snippet"]["publishedAt"],
        "tema_busqueda": "lgtbi",
        "año_busqueda": 2015
    })

df_videos_lgtbi_2015 = pd.DataFrame(videos_lgtbi_2015)

In [ ]:
video_ids = df_videos_lgtbi_2015["video_id"].tolist()

request_stats = youtube.videos().list(
    part="statistics",
    id=",".join(video_ids)
)

response_stats = request_stats.execute()

In [ ]:
estadisticas = []

for item in response_stats["items"]:

    stats = item.get("statistics", {})

    estadisticas.append({
        "video_id": item["id"],
        "visualizaciones": int(stats.get("viewCount", 0)),
        "likes": int(stats.get("likeCount", 0)),
        "comentarios": int(stats.get("commentCount", 0))
    })

df_stats = pd.DataFrame(estadisticas)

In [ ]:
todos_comentarios_lgtbi_2015 = []

for _, video in tqdm(
    df_videos_lgtbi_2015.iterrows(),
    total=len(df_videos_lgtbi_2015)
):

    video_id = video["video_id"]

    try:

        df_temp = extraer_comentarios_video(
            youtube=youtube,
            video_id=video_id,
            max_comentarios=1000
        )

        if not df_temp.empty:

            df_temp["titulo_video"] = video["titulo"]
            df_temp["canal"] = video["canal"]
            df_temp["fecha_video"] = video["fecha_publicacion"]
            df_temp["año_video"] = 2015
            df_temp["tema"] = "lgtbi"

            todos_comentarios_lgtbi_2015.append(df_temp)

        time.sleep(0.2)

    except Exception as e:

        print(f"Error en {video_id}: {e}")

 20%|██        | 10/50 [00:03<00:14,  2.80it/s]

Error en atXkr8ArL5s: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=atXkr8ArL5s&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

100%|██████████| 50/50 [00:23<00:00,  2.09it/s]

In [ ]:
df_youtube_lgtbi_2015 = pd.concat(
    todos_comentarios_lgtbi_2015,
    ignore_index=True
)

df_youtube_lgtbi_2015.shape

(2828, 10)

In [ ]:
df_youtube_lgtbi_2015.to_csv(
    RUTA_RAW / "youtube_lgtbi_2015_comentarios.csv",
    index=False,
    encoding="utf-8-sig"
)

In [35]:
# ==========================================
# NUEVAS BÚSQUEDAS - INMIGRACIÓN 2019
# ==========================================

busquedas_inmigracion = [
    "inmigración ilegal España",
    "menas España",
    "crisis migratoria España",
    "pateras España",
    "refugiados España",
    "VOX inmigración",
    "Abascal inmigración",
    "inmigrantes España"
]

videos_nuevos_2019 = []

for termino in busquedas_inmigracion:

    print(f"Buscando: {termino}")

    request = youtube.search().list(
        part="snippet",
        q=termino,
        type="video",
        maxResults=50,
        relevanceLanguage="es",
        regionCode="ES",
        publishedAfter="2019-01-01T00:00:00Z",
        publishedBefore="2019-12-31T23:59:59Z",
        order="relevance"
    )

    response = request.execute()

    for item in response["items"]:

        videos_nuevos_2019.append({
            "video_id": item["id"]["videoId"],
            "canal": item["snippet"]["channelTitle"],
            "titulo": item["snippet"]["title"],
            "fecha": item["snippet"]["publishedAt"][:10]
        })

df_videos_nuevos_2019 = pd.DataFrame(videos_nuevos_2019)

print("Vídeos encontrados:", len(df_videos_nuevos_2019))
print(
    "Vídeos únicos:",
    df_videos_nuevos_2019["video_id"].nunique()
)

df_videos_nuevos_2019 = (
    df_videos_nuevos_2019
    .drop_duplicates(subset="video_id")
)

df_videos_nuevos_2019.head()

Buscando: inmigración ilegal España
Buscando: menas España
Buscando: crisis migratoria España
Buscando: pateras España
Buscando: refugiados España
Buscando: VOX inmigración
Buscando: Abascal inmigración
Buscando: inmigrantes España
Vídeos encontrados: 400
Vídeos únicos: 350

,video_id,canal,titulo,fecha
0,-ardA7cU6f0,El Toro TV,Más de 30.000 inmigrantes ilegales en 2019: la radiografía de la inmigración ilegal en España,2019-12-18
1,Z5YzLgXEjg4,La Toroteca,"La inmigración ilegal, desbordada en España",2019-04-11
2,dAwlOoeyAiE,La Toroteca,"España, la primera ruta marítima de inmigración ilegal",2019-01-08
3,RomI4fYPJR4,RTVCE,"En 2019 la inmigración irregular se ha reducido un 50,5% en España",2019-12-30
4,-Gytamy7G2E,euronews (en español),España ya no es la principal entrada de inmigrantes irregulares en la UE,2019-06-19

In [36]:
df_videos_nuevos_2019["canal"].value_counts().head(30)

canal
euronews (en español)                      26
Málaga 24h TV Noticias                     21
VOX España                                 14
AGENCIA EFE                                10
CeutaTV                                     8
laSexta                                     7
Onda Algeciras TV                           7
El Toro TV                                  7
RTVCE                                       6
La Toroteca                                 6
laSexta Noticias                            6
Europa Press                                6
EL PAÍS                                     5
COMISION ESPAÑOLA DE AYUDA AL REFUGIADO     5
FRANCE 24 Español                           5
NTN24                                       4
canal33tvelsalvador                         4
Distopía                                    4
Cadena SER                                  3
almeriacanal                                3
Antena 3                                    3
GranCanariaTv.com                           3
Cartagena TV                                3
ACNUR Comité español                        3
Morenazo RXX                                3
grancanariatv 2                             2
InformativosTvc                             2
DMAX España                                 2
partido orden y ley                         2
Save the Children España                    2
Name: count, dtype: int64

In [37]:
df_videos_nuevos_2019.shape

(350, 4)

In [38]:
# IDs de los vídeos originales de inmigración 2019
ids_originales_2019 = set(
    df_videos_2019["video_id"]
)

# Quedarnos solo con vídeos que no estaban en la extracción anterior
df_videos_nuevos_reales_2019 = df_videos_nuevos_2019[
    ~df_videos_nuevos_2019["video_id"].isin(ids_originales_2019)
].copy()

print(
    "Vídeos realmente nuevos:",
    df_videos_nuevos_reales_2019["video_id"].nunique()
)

df_videos_nuevos_reales_2019.shape

Vídeos realmente nuevos: 316

(316, 4)

In [39]:
df_videos_nuevos_reales_2019[
    ["fecha", "canal", "titulo"]
].head(50)

,fecha,canal,titulo
2,2019-01-08,La Toroteca,"España, la primera ruta marítima de inmigración ilegal"
5,2019-08-16,euronews (en español),La entrada de inmigrantes irregulares a España se reduce en un 39 % en lo que va de año
7,2019-07-02,Onda Algeciras TV,El balance de inmigración arroja en el primer semestre de 2019 descienden un 23 % respecto a 2018
8,2019-11-06,RTVCE,Vox apuesta porque la inmigración se afronte atendiendo las necesidades de la economía española
11,2019-11-26,RTVCE,El drama de la inmigración
12,2019-05-15,Diario de Cádiz,Operación de la Policía Nacional contra la inmigración ilegal
13,2019-03-11,TV SENADO CHILE,"Especial - Migración, Inclusión y Desarrollo: una mirada al futuro - 11 de Marzo 2019"
14,2019-02-06,La Toroteca,Sánchez reconoce el &#39;efecto llamada&#39; de la inmigración
15,2019-03-02,CHEIKH DIENG OFFICIAL,"VOX, PP y la inmigración ilegal: el gran problema de España es Francia"
18,2019-08-21,Isabel Allende Bussi,Proyecto Ley Migración y Extranjería 13 de agosto
21,2019-08-20,Imagen Noticias,España envía buque a recoger inmigrantes que viajan a bordo de Open Arms | Yuriria Sierra
22,2019-05-15,Málaga 24h TV Noticias,Noticia - Once detenidos de una red de inmigración ilegal a través de pateras
24,2019-04-26,EsAsturiasTV,INMIGRACIÓN ILEGAL Y MAFIAS en AHORRO Y FINANZAS 25 04 2019
25,2019-06-06,Facultad de Ciencias Sociales UBA,Espóiler sobre Migraciones
26,2019-02-23,TERTULIA MAGALLÁNICA,Temporada 5 (2018) Programa 07; Inmigración española I
30,2019-04-03,NTN24,Propuesta de muro fronterizo entre España y Marruecos
31,2019-05-15,Onda Algeciras TV,Detención de 11 personas en una operación contra una red de inmigración ilegal a través de pateras
35,2019-11-27,FRANCE 24 Español,Libia: miles de migrantes están atrapados en el país africano (3/5)
37,2019-11-27,euronews (en español),Cuatro muertos y 16 desaparecidos intentando llegar a España en patera
38,2019-11-29,euronews (en español),Una patera con 24 personas llega a las costas de Gran Canaria
39,2019-04-24,Código Nuevo,Inmigración ¿Hay sitio para todos? | Reportaje | Código Nuevo
40,2019-02-20,euronews (en español),Baja el número de llegadas de inmigrantes ilegales a la Unión Europea
41,2019-06-27,Angulo & Asociados,Estar ilegal en España? Que sucede?
42,2019-01-05,AGENCIA EFE,"Cae la llegada de migrantes a la UE y se duplica la de España, según Frontex"
43,2019-02-07,Podemos Canarias,Paco Déniz (Podemos) sobre la inmigración ilegal
44,2019-10-22,partido orden y ley,Inmigración Ilegal un problema de tod@s
45,2019-10-22,partido orden y ley,Inmigración Ilegal un problema de tod@s
46,2019-01-09,euronews (en español),Golpe policial al tráfico de inmigrantes en el sur de España
47,2019-06-29,menka1231,El negocio de la inmigración ilegal
48,2019-08-19,Abogada de Inmigración - JessicaDominguezTV,¿Pueden los oficiales de inmigración pedir documentos a pasajeros en autobuses o trenes?
49,2019-08-03,Damian Arroyo,Consecuencias de la inmigración ilegal
50,2019-10-31,Distopía,Qué hacen los MENAS en España?
51,2019-11-26,El Toro TV,El fraude de los menas en España
52,2019-11-08,EL ESPAÑOL,Vox afirma que los MENAS ATEMORIZAN a la población
54,2019-06-15,CHRISTIFIDELES Tau,“MENAS” Menores Extranjeros No Acompañados
55,2019-08-30,Fred De Palma,Fred De Palma &amp; Ana Mena - Se Iluminaba (Official Video)
56,2019-04-11,Grupo Joly,Desmantelada una red que secuestraba a menas en España a cambio de un rescate
57,2019-07-30,Save the Children España,"Mohammed, ex menor migrante tutelado en España"
58,2019-11-07,El Toro TV,¿Cuántos menas hay en España?
59,2019-04-12,almeriacanal,La Policía Nacional desmantela una red que secuestraba a MENAs traficados a España
60,2019-06-12,La Voz Antena 3,Juan Mena canta &#39;Envidia&#39; | Asaltos | La Voz Senior Antena 3 2019
61,2019-04-11,Edurne García Ordóñez,MENAs traficados a España
62,2019-04-07,ramiaschannel,Los MENAS ¿son chicos problemáticos? Visitamos un CENTRO de MENORES | ramiaschannel
63,2019-11-09,El Toro TV,¿Debe España exigir a Marruecos que se haga cargo de los menas?
64,2019-07-16,Roberto Fernández Fernández,Los MENAS se duplican en España en 15 meses ⚫ Tertulia SIN COMPLEJOS
65,2019-04-11,AGENCIA EFE,Desmantelada una red que secuestraba menas traficados a España en pateras
66,2019-08-20,Aragon Noticias,EL PP PIDE MÁS RECURSOS PARA LOS &quot;MENAS&quot;
67,2019-07-31,laSexta Noticias,Las polémicas propuestas de las comunidades para los menores no acompañados
68,2019-02-08,RTVE Play,&#39;18 años y 1 día&#39; COMPLETO | Crónicas
69,2019-08-07,AGENCIA EFE,Fiscal Jefe de Menores alerta de que hay menas víctimas de redes de extorsión

In [40]:
df_videos_nuevos_reales_2019[
    ["fecha", "canal", "titulo"]
].head(50)

,fecha,canal,titulo
2,2019-01-08,La Toroteca,"España, la primera ruta marítima de inmigración ilegal"
5,2019-08-16,euronews (en español),La entrada de inmigrantes irregulares a España se reduce en un 39 % en lo que va de año
7,2019-07-02,Onda Algeciras TV,El balance de inmigración arroja en el primer semestre de 2019 descienden un 23 % respecto a 2018
8,2019-11-06,RTVCE,Vox apuesta porque la inmigración se afronte atendiendo las necesidades de la economía española
11,2019-11-26,RTVCE,El drama de la inmigración
12,2019-05-15,Diario de Cádiz,Operación de la Policía Nacional contra la inmigración ilegal
13,2019-03-11,TV SENADO CHILE,"Especial - Migración, Inclusión y Desarrollo: una mirada al futuro - 11 de Marzo 2019"
14,2019-02-06,La Toroteca,Sánchez reconoce el &#39;efecto llamada&#39; de la inmigración
15,2019-03-02,CHEIKH DIENG OFFICIAL,"VOX, PP y la inmigración ilegal: el gran problema de España es Francia"
18,2019-08-21,Isabel Allende Bussi,Proyecto Ley Migración y Extranjería 13 de agosto
21,2019-08-20,Imagen Noticias,España envía buque a recoger inmigrantes que viajan a bordo de Open Arms | Yuriria Sierra
22,2019-05-15,Málaga 24h TV Noticias,Noticia - Once detenidos de una red de inmigración ilegal a través de pateras
24,2019-04-26,EsAsturiasTV,INMIGRACIÓN ILEGAL Y MAFIAS en AHORRO Y FINANZAS 25 04 2019
25,2019-06-06,Facultad de Ciencias Sociales UBA,Espóiler sobre Migraciones
26,2019-02-23,TERTULIA MAGALLÁNICA,Temporada 5 (2018) Programa 07; Inmigración española I
30,2019-04-03,NTN24,Propuesta de muro fronterizo entre España y Marruecos
31,2019-05-15,Onda Algeciras TV,Detención de 11 personas en una operación contra una red de inmigración ilegal a través de pateras
35,2019-11-27,FRANCE 24 Español,Libia: miles de migrantes están atrapados en el país africano (3/5)
37,2019-11-27,euronews (en español),Cuatro muertos y 16 desaparecidos intentando llegar a España en patera
38,2019-11-29,euronews (en español),Una patera con 24 personas llega a las costas de Gran Canaria
39,2019-04-24,Código Nuevo,Inmigración ¿Hay sitio para todos? | Reportaje | Código Nuevo
40,2019-02-20,euronews (en español),Baja el número de llegadas de inmigrantes ilegales a la Unión Europea
41,2019-06-27,Angulo & Asociados,Estar ilegal en España? Que sucede?
42,2019-01-05,AGENCIA EFE,"Cae la llegada de migrantes a la UE y se duplica la de España, según Frontex"
43,2019-02-07,Podemos Canarias,Paco Déniz (Podemos) sobre la inmigración ilegal
44,2019-10-22,partido orden y ley,Inmigración Ilegal un problema de tod@s
45,2019-10-22,partido orden y ley,Inmigración Ilegal un problema de tod@s
46,2019-01-09,euronews (en español),Golpe policial al tráfico de inmigrantes en el sur de España
47,2019-06-29,menka1231,El negocio de la inmigración ilegal
48,2019-08-19,Abogada de Inmigración - JessicaDominguezTV,¿Pueden los oficiales de inmigración pedir documentos a pasajeros en autobuses o trenes?
49,2019-08-03,Damian Arroyo,Consecuencias de la inmigración ilegal
50,2019-10-31,Distopía,Qué hacen los MENAS en España?
51,2019-11-26,El Toro TV,El fraude de los menas en España
52,2019-11-08,EL ESPAÑOL,Vox afirma que los MENAS ATEMORIZAN a la población
54,2019-06-15,CHRISTIFIDELES Tau,“MENAS” Menores Extranjeros No Acompañados
55,2019-08-30,Fred De Palma,Fred De Palma &amp; Ana Mena - Se Iluminaba (Official Video)
56,2019-04-11,Grupo Joly,Desmantelada una red que secuestraba a menas en España a cambio de un rescate
57,2019-07-30,Save the Children España,"Mohammed, ex menor migrante tutelado en España"
58,2019-11-07,El Toro TV,¿Cuántos menas hay en España?
59,2019-04-12,almeriacanal,La Policía Nacional desmantela una red que secuestraba a MENAs traficados a España
60,2019-06-12,La Voz Antena 3,Juan Mena canta &#39;Envidia&#39; | Asaltos | La Voz Senior Antena 3 2019
61,2019-04-11,Edurne García Ordóñez,MENAs traficados a España
62,2019-04-07,ramiaschannel,Los MENAS ¿son chicos problemáticos? Visitamos un CENTRO de MENORES | ramiaschannel
63,2019-11-09,El Toro TV,¿Debe España exigir a Marruecos que se haga cargo de los menas?
64,2019-07-16,Roberto Fernández Fernández,Los MENAS se duplican en España en 15 meses ⚫ Tertulia SIN COMPLEJOS
65,2019-04-11,AGENCIA EFE,Desmantelada una red que secuestraba menas traficados a España en pateras
66,2019-08-20,Aragon Noticias,EL PP PIDE MÁS RECURSOS PARA LOS &quot;MENAS&quot;
67,2019-07-31,laSexta Noticias,Las polémicas propuestas de las comunidades para los menores no acompañados
68,2019-02-08,RTVE Play,&#39;18 años y 1 día&#39; COMPLETO | Crónicas
69,2019-08-07,AGENCIA EFE,Fiscal Jefe de Menores alerta de que hay menas víctimas de redes de extorsión

## 1. Obtener estadísticas

In [41]:
video_ids = df_videos_nuevos_reales_2019["video_id"].tolist()

estadisticas_nuevas = []

for i in range(0, len(video_ids), 50):

    lote_ids = video_ids[i:i + 50]

    request_stats = youtube.videos().list(
        part="statistics",
        id=",".join(lote_ids)
    )

    response_stats = request_stats.execute()

    for item in response_stats["items"]:

        stats = item.get("statistics", {})

        estadisticas_nuevas.append({
            "video_id": item["id"],
            "visualizaciones": int(stats.get("viewCount", 0)),
            "likes": int(stats.get("likeCount", 0)),
            "comentarios": int(stats.get("commentCount", 0))
        })

df_stats_nuevos_2019 = pd.DataFrame(estadisticas_nuevas)

## 2. Unir estadísticas

In [42]:
df_videos_nuevos_reales_2019 = (
    df_videos_nuevos_reales_2019
    .merge(
        df_stats_nuevos_2019,
        on="video_id",
        how="left"
    )
)

## 3. Seleccionar los 100 con más comentarios

In [43]:
df_seleccion_nuevos_2019 = (
    df_videos_nuevos_reales_2019
    .sort_values(
        "comentarios",
        ascending=False
    )
    .head(100)
    .copy()
)

df_seleccion_nuevos_2019[
    ["canal", "titulo", "comentarios", "visualizaciones"]
].head(30)

,canal,titulo,comentarios,visualizaciones
250,Antena 3,Santiago Abascal: &quot;A los MENAS hay que expulsarlos&quot; - El Hormiguero 3.0,7476,2797150
301,Realidades Con Clau,¡LA CANCIÓN QUE HACE LLORAR A INMIGRANTES! &quot;Alex Rivera&quot; &quot;Pedro Rivera&quot; &quot;La Carta&quot; &quot;El Inmigrante&quot;,5291,17788508
35,Fred De Palma,Fred De Palma &amp; Ana Mena - Se Iluminaba (Official Video),4739,97187456
252,Antena 3,Santiago Abascal sobre adopción gay: &quot;Se prefiere que un niño tenga padre y madre&quot; - El Hormiguero,3532,741443
256,VOX España,⚡ Santiago Abascal destroza a Pedro Sánchez en el Congreso,3179,973424
280,VOX España,Colosal réplica de Santiago Abascal en la tribuna del Congreso 💪🇪🇸,3062,996402
240,Antena 3,Santiago Abascal: &quot;VOX no tiene una posición sobre Franco&quot; - El Hormiguero 3.0,1476,772550
254,VOX España,Santiago Abascal desvela a dónde van las ayudas para la vivienda,1426,271128
286,VOX España,Santiago Abascal responde duramente a los que atacan a VOX,1111,152981
163,N+ UNIVISION,"Mexicanos creen encontrar en España mejor acogida, pero la mayoría de sus solicitudes son rechazadas",1053,39109
272,El Mundo,Un día con Santiago Abascal (Vox) en la Granada &#39;reconquistada&#39;,959,149329
291,La Nicoteca,🤔🤔🤔AYUDAS A INMIGRANTES EN ESPAÑA - La Nicoteca,857,49416
282,GranCanariaTv.com,"&quot;Mujeres, homosexuales y catalanes nos apoyan&quot; Primer discurso de Santiago Abascal (VOX) en Congreso",830,92658
209,Pandolar - El panda del dollar,😱 Mensaje de un inmigrante a VOX,824,46070
246,Madridiario,"Entrevista con Rocío Monasterio, líder de VOX en Madrid",681,55846
249,laSexta,¿Por qué tanta gente vota a Vox? Desgranamos el discurso xenófobo de Santiago Abascal,621,36797
267,COPE,"Herrera entrevista a Santiago Abascal, presidente de Vox",562,153844
68,Espacio del Inmigrante,5 MENTIRAS SOBRE LOS MENAS. Menores Extranjeros No Acompañados.,546,30691
273,VOX España,Santiago Abascal responde a las turbas del &quot;no pasaran&quot;,526,51144
278,VOX España,Abrumador apoyo a VOX y Santiago Abascal en Guadalajara,509,104817
274,VOX España,Santiago Abascal estalla contra el PP y su eslogan &quot;Valor Seguro&quot;,493,63656
271,VOX España,🇪🇸 Minuto de Oro de Santiago Abascal 🇪🇸,485,75425
155,DMAX España,Así es una persecución de narcolanchas en el Estrecho para interceptar droga | Control de Fronteras,477,2722950
261,elDiarioes,Segundo debate de investidura | Intervención completa de Santiago Abascal,458,83001
285,VOX España,¿Quién es realmente Santiago Abascal?,453,64186
166,EL PAÍS,80 años de la llegada de los primero exiliados españoles a México,449,77880
80,laSexta,La crítica del papa Francisco a Europa por la crisis migratoria - Salvados,350,248963
288,VOX España,"⚡ O ellos o nosotros, tú eliges",342,37393
226,Madridiario,La postura de VOX Madrid sobre la inmigración,313,26686
224,LibertadDigital,Vox pide construir un muro en la frontera con Marruecos,312,12016

## 4. Comprobar volumen

In [44]:
print(
    "Comentarios potenciales:",
    df_seleccion_nuevos_2019["comentarios"].sum()
)

print(
    "Vídeos seleccionados:",
    df_seleccion_nuevos_2019["video_id"].nunique()
)

Comentarios potenciales: 48170
Vídeos seleccionados: 100

In [45]:
# ==================================================
# EXTRAER COMENTARIOS DE NUEVOS VÍDEOS - 2019
# ==================================================

todos_comentarios_nuevos_2019 = []

for _, video in tqdm(
    df_seleccion_nuevos_2019.iterrows(),
    total=len(df_seleccion_nuevos_2019)
):

    video_id = video["video_id"]

    try:

        df_temp = extraer_comentarios_video(
            youtube=youtube,
            video_id=video_id,
            max_comentarios=1000
        )

        if not df_temp.empty:

            df_temp["titulo_video"] = video["titulo"]
            df_temp["canal"] = video["canal"]
            df_temp["fecha_video"] = video["fecha"]
            df_temp["año_video"] = 2019
            df_temp["tema"] = "inmigracion"

            todos_comentarios_nuevos_2019.append(df_temp)

        time.sleep(0.2)

    except Exception as e:
        print(f"Error en {video_id}: {e}")

 65%|██████▌   | 65/100 [00:59<00:12,  2.79it/s]

Error en vtWeHxI4Zxs: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=vtWeHxI4Zxs&maxResults=100&textFormat=plainText&order=relevance&key=AIzaSyAxOxINDuUteuE3P0MrU7GKS9H9VILkYAo&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

100%|██████████| 100/100 [01:11<00:00,  1.40it/s]

In [46]:
df_youtube_nuevos_2019 = pd.concat(
    todos_comentarios_nuevos_2019,
    ignore_index=True
)

df_youtube_nuevos_2019.shape

(13313, 10)

In [47]:
df_youtube_nuevos_2019["video_id"].nunique()

99

In [51]:
df_youtube_nuevos_2019.to_csv(
    RUTA_RAW / "youtube_inmigracion_2019_ampliacion.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Ampliación 2019 guardada")

Ampliación 2019 guardada

In [52]:
df_youtube_2019_ampliado = pd.concat(
    [
        df_youtube_2019,
        df_youtube_nuevos_2019
    ],
    ignore_index=True
)

df_youtube_2019_ampliado = (
    df_youtube_2019_ampliado
    .drop_duplicates(
        subset=["video_id", "texto"]
    )
)

print(df_youtube_2019_ampliado.shape)

(20151, 10)

In [53]:
df_youtube_2019_ampliado.to_csv(
    RUTA_RAW / "youtube_inmigracion_2019_ampliado.csv",
    index=False,
    encoding="utf-8-sig"
)